// <auto-generated />
using System;
using BillGenerator.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BillGenerator.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("BillGenerator.Domain.Entities.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DiscountType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TaxRatePercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique()
                        .HasFilter("[InvoiceNumber] IS NOT NULL");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("BillGenerator.Domain.Entities.BillLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BillId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CatalogItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("CatalogItemId");

                    b.ToTable("BillLines");
                });

            modelBuilder.Entity("BillGenerator.Domain.Entities.CatalogItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CatalogType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DefaultPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CatalogType", "IsActive");

                    b.ToTable("CatalogItems");
                });

            modelBuilder.Entity("BillGenerator.Domain.Entities.DailyInvoiceCounter", b =>
                {
                    b.Property<DateTime>("DateUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastSequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("DateUtc");

                    b.ToTable("DailyInvoiceCounters");
                });

            modelBuilder.Entity("BillGenerator.Domain.Entities.BillLine", b =>
                {
                    b.HasOne("BillGenerator.Domain.Entities.Bill", "Bill")
                        .WithMany("Lines")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BillGenerator.Domain.Entities.CatalogItem", "CatalogItem")
                        .WithMany("BillLines")
                        .HasForeignKey("CatalogItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Bill");

                    b.Navigation("CatalogItem");
                });

            modelBuilder.Entity("BillGenerator.Domain.Entities.Bill", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("BillGenerator.Domain.Entities.CatalogItem", b =>
                {
                    b.Navigation("BillLines");
                });
#pragma warning restore 612, 618
        }
    }
}
