namespace HospitalManagement.API.Models
{
    /*
        Stores prescription details generated by doctors.
    */

    public class Prescription
    {
        public int Id { get; set; }

        public int AppointmentId { get; set; }

        public Appointment? Appointment { get; set; }

        // Medicines prescribed
        public string Medicines { get; set; } = string.Empty;

        // Additional instructions
        public string Instructions { get; set; } = string.Empty;

        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    }
}